[package]
name = "ch3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hex-string = "0.1.0"
hex-literal = "0.3.3"
pretty-hex = "0.2.1"
